[tool.poetry]
name = "my-flask-app"
version = "1.0.0"
description = "A Flask web application"
authors = ["Oscar Andres Macias Narvaez <omaciasnarvaez@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
numpy = "^2.2.0"
pandas = "^2.2.3"
flask = "^3.0.3"
python-dotenv = "^1.0.1"
pika = "^1.3.2"
psycopg2-binary = "^2.9.10"  # Cambiar a psycopg2-binary
safety = "^3.2.8"

[tool.poetry.dev-dependencies]
pytest = "^8.3.3"

[tool.poetry.group.dev.dependencies]
safety = "^3.2.12"
bandit = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
